version: "3"

services:
  db:
    container_name: db
    image: docker.repos.balad.ir/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: stylight_db
      MYSQL_ROOT_PASSWORD: null
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
